"""
Given DNA string and its substring find all the occurences of the substring.
"""


def find_substring_inds(str, substr):
    subst_inds = []
    len_substr = len(substr)
    for i in range(len(str) - len_substr):
        if str[i:i+len_substr] == substr:
            subst_inds.append(i+1)
    return subst_inds


if __name__ == "__main__":
    #print(find_substring_inds('GATATATGCATATACTT', 'ATAT'))

    print(' '.join(list(map(str, find_substring_inds('CGCTTGACACCTGACACCATGACACCTGACACCGTAGCCAGGTGACACCCGTGACACCGGAAGGTCGTGACACCATCCCTTGACACCCAATTTGACACCAATGACACCTGACACCCGGATGACACCGTGACACCATGACACCGTGACACCTGACACCTTTGTTGACACCCTGAGGTATGACACCCGACTGACACCTGACACCATGTGACACCCTGACACCATGTTTCTTGACACCTGACACCTGACACCTGACACCTGACACCGTGACACCCAGGCTGATGACACCTGACACCGTTGGTGACACCTGACACCACTGACACCGTCTGACACCTTGACGCTGACACCAGTAAACATGACACCTGTTAAGAATGTGACACCGCGTGACACCCTGACACCGTGTGACACCTTGACACCGCGTCCGTCGTGATGACACCGATTGACACCTGACACCTGACACCTGACACCGTGACACCGTGTGACACCTGACACCCAGCTTGACACCTGACACCTGACACCTGACACCAGCAACGGTGACACCTGCTACTAGTGACACCGATATGACACCTGGCTGACACCCATGACACCTTGACACCTTGACACCCGGCTGACACCCTAGTGTGACACCCCGGGCTGACACCTGGTTGACACCTTTGACACCAGTGACACCTTACCCTGACACCGTGACACCGCTGACACCTTGACACCTTCGGTGACACCCGCTGACACCGTGACACCTGACACCTGACACCGGATAATGACACCACATGACACCCTGGTGACACCGTGACACCTGACACCATGACACCGGGCTGACACCTTTGACACCTGACACCTTGACACCTTTCCTGACACCTGACACCCTTGACACCAGTAGCTCTGACACCTCTGACACCTGACACCCGAACCATGACACCTGACACCGCCCCAGTGACACCCCTGACACCTGACACCTTGCTGACACCTTTTATGACACCG', 'TGACACCTG')))))
